/* Auto generated by export_rade_v2_constants.py */
#ifndef RADE_V2_CONSTANTS_DATA_H
#define RADE_V2_CONSTANTS_DATA_H

#include "rade_v2_comp.h"

#define RADE_V2_CONST_M  128
#define RADE_V2_CONST_NC 14

extern const RADE_COMP RADE_V2_WFWD[1792];  /* (M,Nc) çsóDêÊ */
extern const RADE_COMP RADE_V2_WINV[1792];  /* (Nc,M) çsóDêÊ */
extern const RADE_COMP RADE_V2_PEND[128];
#define RADE_V2_EOO_LEN 960
extern const RADE_COMP RADE_V2_EOO[960];

#endif
