"""
export_rade_v2_constants.py

RADE V2 の定数行列(Wfwd, Winv, pend)を C 静的配列として書き出す。

これまでの gen_*_ref.py は毎回 Python から model.Wfwd 等を読んで .f32 に
書き出していたが、DLL化(rade_api_v2)では Python/torch がランタイムに
存在しないため、これらの定数を C ソースとして恒久的に埋め込む必要がある。

生成物: rade_v2_constants_data.c / rade_v2_constants_data.h
    - RADE_V2_WFWD[M*Nc]  (extract用, M行Nc列, 複素, 行優先: re,imが交互ではなく
                            float2構造体配列として書く)
    - RADE_V2_WINV[Nc*M]  (送信IDFT用, Nc行M列, 複素)
    - RADE_V2_PEND[M]     (EOO検出用, 複素)

使い方 (radae ルートで):
    python export_rade_v2_constants.py 250725/checkpoints/checkpoint_epoch_200.pth src_v2
"""
import sys, os
import numpy as np
import torch

def main():
    if len(sys.argv) < 3:
        print("usage: python export_rade_v2_constants.py <model.pth> <output_dir>", file=sys.stderr)
        sys.exit(1)
    model_path = sys.argv[1]
    output_dir = sys.argv[2]
    os.makedirs(output_dir, exist_ok=True)

    sys.path.append(".")
    from radae import RADAE

    model = RADAE(21, 56, EbNodB=100, Nzmf=1, rate_Fs=True,
                  cyclic_prefix=0.004, w1_dec=128, w1_dec_stateful=128, peak=True)
    checkpoint = torch.load(model_path, weights_only=True, map_location=torch.device('cpu'))
    state_dict = checkpoint['state_dict']
    model_dict = model.state_dict()
    pretrained_dict = {k: v for k, v in state_dict.items()
                       if k in model_dict and v.shape == model_dict[k].shape}
    model_dict.update(pretrained_dict)
    model.load_state_dict(model_dict, strict=False)

    Wfwd = model.Wfwd.detach().numpy().astype(np.complex64)   # (M, Nc)
    Winv = model.Winv.detach().numpy().astype(np.complex64)   # (Nc, M)
    pend = model.pend.detach().numpy().astype(np.complex64)   # (M,)
    eoo_v2 = model.eoo_v2.detach().numpy().flatten().astype(np.complex64)  # (Ns*sym_len,)
    M, Nc = Wfwd.shape

    def emit_complex_array(f, name, arr_flat):
        f.write(f"const RADE_COMP {name}[{len(arr_flat)}] = {{\n")
        for i, v in enumerate(arr_flat):
            f.write(f"  {{{v.real:.10e}f, {v.imag:.10e}f}}")
            f.write(",\n" if i != len(arr_flat)-1 else "\n")
        f.write("};\n\n")

    h_path = os.path.join(output_dir, "rade_v2_constants_data.h")
    c_path = os.path.join(output_dir, "rade_v2_constants_data.c")

    with open(h_path, "w") as f:
        f.write("/* Auto generated by export_rade_v2_constants.py */\n")
        f.write("#ifndef RADE_V2_CONSTANTS_DATA_H\n#define RADE_V2_CONSTANTS_DATA_H\n\n")
        f.write('#include "rade_v2_comp.h"\n\n')
        f.write(f"#define RADE_V2_CONST_M  {M}\n")
        f.write(f"#define RADE_V2_CONST_NC {Nc}\n\n")
        f.write(f"extern const RADE_COMP RADE_V2_WFWD[{M*Nc}];  /* (M,Nc) 行優先 */\n")
        f.write(f"extern const RADE_COMP RADE_V2_WINV[{Nc*M}];  /* (Nc,M) 行優先 */\n")
        f.write(f"extern const RADE_COMP RADE_V2_PEND[{M}];\n")
        f.write(f"#define RADE_V2_EOO_LEN {len(eoo_v2)}\n")
        f.write(f"extern const RADE_COMP RADE_V2_EOO[{len(eoo_v2)}];\n\n")
        f.write("#endif\n")

    with open(c_path, "w") as f:
        f.write("/* Auto generated by export_rade_v2_constants.py */\n")
        f.write('#include "rade_v2_constants_data.h"\n\n')
        emit_complex_array(f, "RADE_V2_WFWD", Wfwd.reshape(-1))
        emit_complex_array(f, "RADE_V2_WINV", Winv.reshape(-1))
        emit_complex_array(f, "RADE_V2_PEND", pend.reshape(-1))
        emit_complex_array(f, "RADE_V2_EOO", eoo_v2)

    print(f"M={M} Nc={Nc} eoo_len={len(eoo_v2)}")
    print(f"wrote {h_path}")
    print(f"wrote {c_path}")

if __name__ == "__main__":
    main()
